---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ec2
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ec2:v1.21.1
  runtimeConfigRef:
    name: provider-aws
    apiVersion: pkg.crossplane.io/v1
    kind: DeploymentRuntimeConfig
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-eks
spec:
  package: xpkg.upbound.io/upbound/provider-aws-eks:v1.21.1
  runtimeConfigRef:
    name: provider-aws
    apiVersion: pkg.crossplane.io/v1
    kind: DeploymentRuntimeConfig
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-iam
spec:
  package: xpkg.upbound.io/upbound/provider-aws-iam:v1.21.1
  runtimeConfigRef:
    name: provider-aws
    apiVersion: pkg.crossplane.io/v1
    kind: DeploymentRuntimeConfig    
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-ec2
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds

---
apiVersion: eks.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-eks
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds

---
apiVersion: iam.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-iam
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
