---
apiVersion: altimetrik.com/v1alpha1
kind: ClusterClaim
metadata:
  name: cluster-01
spec:
  id: cluster-01
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: small
    minNodeCount: 3
    tags:
      Environment: Development
      Owner: dchin@altimetrik.com
      Project: DEP
      Application: DEP-DEMO